config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/user.rb
class User < ActiveRecord::Base
  include TokenAuthenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook, :twitter, :instagram]

  before_save :ensure_authentication_token

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth[:provider], uid: auth[:uid]).first_or_initialize.tap do |user|
      user = User.load_user_from_omniauth(user, auth)
    end
  end

  private

    def self.load_user_from_omniauth(user, auth)
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.email = auth.info.email if user.email.blank?
      user.email = auth.info.nickname + "@#{auth.provider}.com" if user.email.blank?
      user.password = Devise.friendly_token[0,20] if user.password.blank?
      user.remote_image_url = auth.info.image.gsub('http://','https://') if user.remote_image_url.blank?
      return user
    end

end

app/controllers/api/users_controller.rb
module Api
class UsersController < BaseController
  before_action :auth_only!, except: [:create]
 # load_and_authorize_resource
 
  def create
    @user = User.new(user_params)
    @user.skip_confirmation!
    if @user.save
      # UserMailer.signup_confirmation(@user).deliver_now
      render_or_false(@user, "api/users/show")
    else
      render json: @user.errors.full_messages.to_sentence, status: 400 and return
    end
  end

  def update
    @user = current_user
    render json: "User not found", status: 400 and return if @user.blank?
    
    if @user.update_attributes(user_params)
      render_or_false(@user, "api/users/show")
    else
      render json: @user.errors.full_messages.to_sentence, status: 400 and return
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render_or_false(@user, "api/users/show")
  end

  protected
  def user_params
    params.require(:user) \
          .permit( :email, :password, :password_confirmation, :image,
                   :first_name, :last_name, :about_me)
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def edit
    @user = current_user
  end

  def update()
    prepare_params
    if @user.update_attributes(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit( :email, :password, :password_confirmation, :image, :remove_image)
    end

    def load_user
      user = User.find(params[:id])
    end

    def prepare_params
      if params[:user][:password].blank? && \
        params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end

  end

end

app/views/users/edit.html.haml
.row
  .col-md-4.col-md-offset-4
    = form_for @user, html: {multipart: true } do |f|
      - add_error(@user.errors.full_messages.to_sentence, 'alert') if @user.errors.any?

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-user
        = f.email_field :email, autofocus: true, placeholder: "#{t ".email"}", autocomplete: "off", class: "form-control"

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-lock
        = f.password_field :password, autocomplete: "off", placeholder: "#{t ".new_password"}", class: "form-control"

      .form-group.input-group.input-group-lg
        %span.input-group-addon
          %i.fa.fa-lock
        = f.password_field :password, autocomplete: "off", placeholder: "#{t ".confirm_new_password"}", class: "form-control"

      .form-group
        .fileupload.fileupload-new{data: {provides: 'fileupload'}}
          .fileupload-preview.thumbnail.thumb-preview{style: "width: 80px; height: 77px"}
            - if @user.try(:image).present?
              = image_tag @user.image.url
            - else
              = image_tag "fallback/avatar.png"
          %div
            %span.btn.btn-file.btn-default.btn-sm
              %span.fileupload-new
                %span.glyphicon.glyphicon-picture
                = t ".image"
              %span.fileupload-exists
                %span.glyphicon.glyphicon-open
                = t '.change'
              = f.file_field :image
            = link_to "#", class: "btn fileupload-exists btn-danger btn-sm", data: {dismiss: 'fileupload'} do
              %span.glyphicon.glyphicon-remove
              = t '.remove'

      - if @user.try(:image).present?
        .form-group
          .checkbox
            %label
              = f.check_box :remove_image
              = t ".remove_image"

      .form-group
        = f.submit (t ".button_update"), class: "btn btn-success full-width"

      .form-group
        = link_to (t ".button_sign_out"), signout_path, class: "btn btn-default"