config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/views/shared/_flash_notice.html.haml
- if flash[:notice].present? || flash[:alert].present? || flash[:error].present?
  - [:notice, :alert, :error].each do |key|
    - next if flash[key].blank?
    .flash-container
      .flash{class: key}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
        = flash[key]

      - flash[key] = nil

app/views/shared/_header.html.haml
%header.navbar.navbar-inverse
  .container
    .navbar-brand
      = link_to "Course Management", root_path, style: "color: white; font-size: 20px;"
    %nav
      .navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Hello
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to edit_user_path(current_user) do
                    %i.fa.fa-pencil-square-o.fa-lg{"aria-hidden" => "true"}
                    Edit Profile
                %li.divider
                %li
                  = link_to destroy_user_session_path, method: :delete do
                    %i.fa.fa-sign-out.fa-lg{"aria-hidden" => "true"}
                    Sign Out
          - else
            %li= link_to "Sign In", new_user_session_path

app/views/shared/_languages.html.haml
= link_to_unless_current "En", sessions_path("en")

app/views/shared/_logo.html.haml
.form-group
  %i.fa.fa-star
  STARTER-KIT